package org.example.datapipeline.config;

import jakarta.xml.bind.annotation.*;
import org.example.datapipeline.config.action.Action;
import org.example.datapipeline.config.input.Input;
import org.example.datapipeline.config.output.Output;
import org.example.datapipeline.executor.action.ActionExecutor;
import org.example.datapipeline.executor.action.ActionRegistry;
import org.example.datapipeline.executor.context.ExecutionContext;

/**
 * Represents a task within a pipeline stage.
 *
 * A task defines a single unit of work executed as part of a stage.
 * It specifies the input source, the action to be performed, and the
 * output produced after execution.
 *
 * Tasks within a stage are executed sequentially in the order they
 * appear in the pipeline configuration.
 *
 * Features:
 * - Input: Defines the data source consumed by the task.
 *
 * - Action: Specifies the operation to perform along with its method and parameters.
 *
 * - Output: Defines where the result of the task execution will be written.
 *
 * - Execution: Dynamically resolves the appropriate action implementation using the
 *              action type and executes it via a shared execution context.
 *
 * The design supports extensibility by allowing new action types to be
 * registered in the action registry without modifying the task logic.
 *
 * This class is mapped from the <task> element in the pipeline XML.
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Task {

    @XmlElement
    private Input input;

    @XmlElement
    private Action action;

    @XmlElement
    private Output output;

    /**
     * Returns the input configuration for the task.
     *
     * @return input source used by the task
     */
    public Input getInput() {
        return input;
    }

    /**
     * Returns the action to be executed by the task.
     *
     * @return action definition for the task
     */
    public Action getAction() {
        return action;
    }

    /**
     * Returns the output produced by the task.
     *
     * @return output destination generated by the task
     */
    public Output getOutput() {
        return output;
    }

    /**
     * Executes this task by resolving the action from the registry and running it.
     *
     * <p>This method exists primarily for unit-test convenience. In production pipelines,
     * task execution is orchestrated by
     * {@link org.example.datapipeline.executor.PipelineExecutor#executeStage} which
     * wraps execution with metrics collection, retry logic, and run recording.
     *
     * <p>The method:
     * <ol>
     *   <li>Looks up the {@link ActionExecutor} implementation for {@code action.getType()}.</li>
     *   <li>Creates a new {@link ExecutionContext} containing this task's input, output,
     *       and method configuration.</li>
     *   <li>Calls {@link ActionExecutor#execute(ExecutionContext)} to run the action.</li>
     * </ol>
     *
     * @throws RuntimeException if the action type is not registered, required parameters are
     *                          missing, or the underlying operation fails
     */
    public void execute() {

        ActionExecutor actionImpl = ActionRegistry.getAction(action.getType());
        ExecutionContext ctx = new ExecutionContext(input, output, action.getMethod());
        actionImpl.execute(ctx);
    }
}