package org.example.datapipeline.config;

import jakarta.xml.bind.annotation.*;

/**
 * Represents a task within a pipeline stage.
 *
 * A task defines a single unit of work executed as part of a stage.
 * It specifies the input source, the action to be performed, and the
 * output produced after execution.
 *
 * Tasks within a stage are executed sequentially in the order they
 * appear in the pipeline configuration.
 *
 * This class is mapped from the <task> element in the pipeline XML.
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Task {

    @XmlElement
    private Input input;

    @XmlElement
    private Action action;

    @XmlElement
    private Output output;

    /**
     * Returns the input configuration for the task.
     *
     * @return input source used by the task
     */
    public Input getInput() {
        return input;
    }

    /**
     * Returns the action to be executed by the task.
     *
     * @return action definition for the task
     */
    public Action getAction() {
        return action;
    }

    /**
     * Returns the output produced by the task.
     *
     * @return output destination generated by the task
     */
    public Output getOutput() {
        return output;
    }
}